# Use an official ubuntu runtime as a parent image
FROM ubuntu:16.04

# Run echo when the container launches. The first argument to ENRTYPOINY is the executable; the next is an argument.
# See https://docs.docker.com/engine/reference/builder/#entrypoint for an example
ENTRYPOINT ["echo","'I am a simple container'"]
